/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookConsultationRouteImport } from './routes/book-consultation'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ServicesSlugRouteImport } from './routes/services/$slug'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminNavigationRouteImport } from './routes/admin/navigation'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminContactRouteImport } from './routes/admin/contact'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as AdminTestimonialsIndexRouteImport } from './routes/admin/testimonials.index'
import { Route as AdminServicesIndexRouteImport } from './routes/admin/services.index'
import { Route as AdminResourcesIndexRouteImport } from './routes/admin/resources.index'
import { Route as AdminPagesIndexRouteImport } from './routes/admin/pages.index'
import { Route as AdminFaqsIndexRouteImport } from './routes/admin/faqs.index'
import { Route as AdminConsultationTypesIndexRouteImport } from './routes/admin/consultation-types.index'
import { Route as AdminBlogIndexRouteImport } from './routes/admin/blog.index'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as ApiPublicCalendlyRouteImport } from './routes/api/public/calendly'
import { Route as AdminTestimonialsIdRouteImport } from './routes/admin/testimonials.$id'
import { Route as AdminServicesIdRouteImport } from './routes/admin/services.$id'
import { Route as AdminResourcesIdRouteImport } from './routes/admin/resources.$id'
import { Route as AdminPagesIdRouteImport } from './routes/admin/pages.$id'
import { Route as AdminFaqsIdRouteImport } from './routes/admin/faqs.$id'
import { Route as AdminConsultationTypesIdRouteImport } from './routes/admin/consultation-types.$id'
import { Route as AdminBlogIdRouteImport } from './routes/admin/blog.$id'

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookConsultationRoute = BookConsultationRouteImport.update({
  id: '/book-consultation',
  path: '/book-consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNavigationRoute = AdminNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactRoute = AdminContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsIndexRoute = AdminTestimonialsIndexRouteImport.update({
  id: '/testimonials/',
  path: '/testimonials/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesIndexRoute = AdminServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResourcesIndexRoute = AdminResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesIndexRoute = AdminPagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqsIndexRoute = AdminFaqsIndexRouteImport.update({
  id: '/faqs/',
  path: '/faqs/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConsultationTypesIndexRoute =
  AdminConsultationTypesIndexRouteImport.update({
    id: '/consultation-types/',
    path: '/consultation-types/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCalendlyRoute = ApiPublicCalendlyRouteImport.update({
  id: '/api/public/calendly',
  path: '/api/public/calendly',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestimonialsIdRoute = AdminTestimonialsIdRouteImport.update({
  id: '/testimonials/$id',
  path: '/testimonials/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesIdRoute = AdminServicesIdRouteImport.update({
  id: '/services/$id',
  path: '/services/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResourcesIdRoute = AdminResourcesIdRouteImport.update({
  id: '/resources/$id',
  path: '/resources/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesIdRoute = AdminPagesIdRouteImport.update({
  id: '/pages/$id',
  path: '/pages/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqsIdRoute = AdminFaqsIdRouteImport.update({
  id: '/faqs/$id',
  path: '/faqs/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConsultationTypesIdRoute =
  AdminConsultationTypesIdRouteImport.update({
    id: '/consultation-types/$id',
    path: '/consultation-types/$id',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/book-consultation': typeof BookConsultationRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/consultation-types/$id': typeof AdminConsultationTypesIdRoute
  '/admin/faqs/$id': typeof AdminFaqsIdRoute
  '/admin/pages/$id': typeof AdminPagesIdRoute
  '/admin/resources/$id': typeof AdminResourcesIdRoute
  '/admin/services/$id': typeof AdminServicesIdRoute
  '/admin/testimonials/$id': typeof AdminTestimonialsIdRoute
  '/api/public/calendly': typeof ApiPublicCalendlyRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/consultation-types/': typeof AdminConsultationTypesIndexRoute
  '/admin/faqs/': typeof AdminFaqsIndexRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
  '/admin/resources/': typeof AdminResourcesIndexRoute
  '/admin/services/': typeof AdminServicesIndexRoute
  '/admin/testimonials/': typeof AdminTestimonialsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-consultation': typeof BookConsultationRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/services': typeof ServicesIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/consultation-types/$id': typeof AdminConsultationTypesIdRoute
  '/admin/faqs/$id': typeof AdminFaqsIdRoute
  '/admin/pages/$id': typeof AdminPagesIdRoute
  '/admin/resources/$id': typeof AdminResourcesIdRoute
  '/admin/services/$id': typeof AdminServicesIdRoute
  '/admin/testimonials/$id': typeof AdminTestimonialsIdRoute
  '/api/public/calendly': typeof ApiPublicCalendlyRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/consultation-types': typeof AdminConsultationTypesIndexRoute
  '/admin/faqs': typeof AdminFaqsIndexRoute
  '/admin/pages': typeof AdminPagesIndexRoute
  '/admin/resources': typeof AdminResourcesIndexRoute
  '/admin/services': typeof AdminServicesIndexRoute
  '/admin/testimonials': typeof AdminTestimonialsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/book-consultation': typeof BookConsultationRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/consultation-types/$id': typeof AdminConsultationTypesIdRoute
  '/admin/faqs/$id': typeof AdminFaqsIdRoute
  '/admin/pages/$id': typeof AdminPagesIdRoute
  '/admin/resources/$id': typeof AdminResourcesIdRoute
  '/admin/services/$id': typeof AdminServicesIdRoute
  '/admin/testimonials/$id': typeof AdminTestimonialsIdRoute
  '/api/public/calendly': typeof ApiPublicCalendlyRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/consultation-types/': typeof AdminConsultationTypesIndexRoute
  '/admin/faqs/': typeof AdminFaqsIndexRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
  '/admin/resources/': typeof AdminResourcesIndexRoute
  '/admin/services/': typeof AdminServicesIndexRoute
  '/admin/testimonials/': typeof AdminTestimonialsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/book-consultation'
    | '/contact'
    | '/faqs'
    | '/privacy-policy'
    | '/resources'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/admin/bookings'
    | '/admin/contact'
    | '/admin/login'
    | '/admin/navigation'
    | '/admin/settings'
    | '/admin/users'
    | '/blog/$slug'
    | '/p/$slug'
    | '/services/$slug'
    | '/admin/'
    | '/blog/'
    | '/services/'
    | '/admin/blog/$id'
    | '/admin/consultation-types/$id'
    | '/admin/faqs/$id'
    | '/admin/pages/$id'
    | '/admin/resources/$id'
    | '/admin/services/$id'
    | '/admin/testimonials/$id'
    | '/api/public/calendly'
    | '/api/public/stripe-webhook'
    | '/admin/blog/'
    | '/admin/consultation-types/'
    | '/admin/faqs/'
    | '/admin/pages/'
    | '/admin/resources/'
    | '/admin/services/'
    | '/admin/testimonials/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book-consultation'
    | '/contact'
    | '/faqs'
    | '/privacy-policy'
    | '/resources'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/admin/bookings'
    | '/admin/contact'
    | '/admin/login'
    | '/admin/navigation'
    | '/admin/settings'
    | '/admin/users'
    | '/blog/$slug'
    | '/p/$slug'
    | '/services/$slug'
    | '/admin'
    | '/blog'
    | '/services'
    | '/admin/blog/$id'
    | '/admin/consultation-types/$id'
    | '/admin/faqs/$id'
    | '/admin/pages/$id'
    | '/admin/resources/$id'
    | '/admin/services/$id'
    | '/admin/testimonials/$id'
    | '/api/public/calendly'
    | '/api/public/stripe-webhook'
    | '/admin/blog'
    | '/admin/consultation-types'
    | '/admin/faqs'
    | '/admin/pages'
    | '/admin/resources'
    | '/admin/services'
    | '/admin/testimonials'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/book-consultation'
    | '/contact'
    | '/faqs'
    | '/privacy-policy'
    | '/resources'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/admin/bookings'
    | '/admin/contact'
    | '/admin/login'
    | '/admin/navigation'
    | '/admin/settings'
    | '/admin/users'
    | '/blog/$slug'
    | '/p/$slug'
    | '/services/$slug'
    | '/admin/'
    | '/blog/'
    | '/services/'
    | '/admin/blog/$id'
    | '/admin/consultation-types/$id'
    | '/admin/faqs/$id'
    | '/admin/pages/$id'
    | '/admin/resources/$id'
    | '/admin/services/$id'
    | '/admin/testimonials/$id'
    | '/api/public/calendly'
    | '/api/public/stripe-webhook'
    | '/admin/blog/'
    | '/admin/consultation-types/'
    | '/admin/faqs/'
    | '/admin/pages/'
    | '/admin/resources/'
    | '/admin/services/'
    | '/admin/testimonials/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookConsultationRoute: typeof BookConsultationRoute
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ResourcesRoute: typeof ResourcesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  PSlugRoute: typeof PSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ApiPublicCalendlyRoute: typeof ApiPublicCalendlyRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-consultation': {
      id: '/book-consultation'
      path: '/book-consultation'
      fullPath: '/book-consultation'
      preLoaderRoute: typeof BookConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/navigation': {
      id: '/admin/navigation'
      path: '/navigation'
      fullPath: '/admin/navigation'
      preLoaderRoute: typeof AdminNavigationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact': {
      id: '/admin/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminContactRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials/': {
      id: '/admin/testimonials/'
      path: '/testimonials'
      fullPath: '/admin/testimonials/'
      preLoaderRoute: typeof AdminTestimonialsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services/': {
      id: '/admin/services/'
      path: '/services'
      fullPath: '/admin/services/'
      preLoaderRoute: typeof AdminServicesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resources/': {
      id: '/admin/resources/'
      path: '/resources'
      fullPath: '/admin/resources/'
      preLoaderRoute: typeof AdminResourcesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages/': {
      id: '/admin/pages/'
      path: '/pages'
      fullPath: '/admin/pages/'
      preLoaderRoute: typeof AdminPagesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faqs/': {
      id: '/admin/faqs/'
      path: '/faqs'
      fullPath: '/admin/faqs/'
      preLoaderRoute: typeof AdminFaqsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/consultation-types/': {
      id: '/admin/consultation-types/'
      path: '/consultation-types'
      fullPath: '/admin/consultation-types/'
      preLoaderRoute: typeof AdminConsultationTypesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calendly': {
      id: '/api/public/calendly'
      path: '/api/public/calendly'
      fullPath: '/api/public/calendly'
      preLoaderRoute: typeof ApiPublicCalendlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/testimonials/$id': {
      id: '/admin/testimonials/$id'
      path: '/testimonials/$id'
      fullPath: '/admin/testimonials/$id'
      preLoaderRoute: typeof AdminTestimonialsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services/$id': {
      id: '/admin/services/$id'
      path: '/services/$id'
      fullPath: '/admin/services/$id'
      preLoaderRoute: typeof AdminServicesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resources/$id': {
      id: '/admin/resources/$id'
      path: '/resources/$id'
      fullPath: '/admin/resources/$id'
      preLoaderRoute: typeof AdminResourcesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages/$id': {
      id: '/admin/pages/$id'
      path: '/pages/$id'
      fullPath: '/admin/pages/$id'
      preLoaderRoute: typeof AdminPagesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faqs/$id': {
      id: '/admin/faqs/$id'
      path: '/faqs/$id'
      fullPath: '/admin/faqs/$id'
      preLoaderRoute: typeof AdminFaqsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/consultation-types/$id': {
      id: '/admin/consultation-types/$id'
      path: '/consultation-types/$id'
      fullPath: '/admin/consultation-types/$id'
      preLoaderRoute: typeof AdminConsultationTypesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminContactRoute: typeof AdminContactRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNavigationRoute: typeof AdminNavigationRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogIdRoute: typeof AdminBlogIdRoute
  AdminConsultationTypesIdRoute: typeof AdminConsultationTypesIdRoute
  AdminFaqsIdRoute: typeof AdminFaqsIdRoute
  AdminPagesIdRoute: typeof AdminPagesIdRoute
  AdminResourcesIdRoute: typeof AdminResourcesIdRoute
  AdminServicesIdRoute: typeof AdminServicesIdRoute
  AdminTestimonialsIdRoute: typeof AdminTestimonialsIdRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminConsultationTypesIndexRoute: typeof AdminConsultationTypesIndexRoute
  AdminFaqsIndexRoute: typeof AdminFaqsIndexRoute
  AdminPagesIndexRoute: typeof AdminPagesIndexRoute
  AdminResourcesIndexRoute: typeof AdminResourcesIndexRoute
  AdminServicesIndexRoute: typeof AdminServicesIndexRoute
  AdminTestimonialsIndexRoute: typeof AdminTestimonialsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminContactRoute: AdminContactRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNavigationRoute: AdminNavigationRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogIdRoute: AdminBlogIdRoute,
  AdminConsultationTypesIdRoute: AdminConsultationTypesIdRoute,
  AdminFaqsIdRoute: AdminFaqsIdRoute,
  AdminPagesIdRoute: AdminPagesIdRoute,
  AdminResourcesIdRoute: AdminResourcesIdRoute,
  AdminServicesIdRoute: AdminServicesIdRoute,
  AdminTestimonialsIdRoute: AdminTestimonialsIdRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminConsultationTypesIndexRoute: AdminConsultationTypesIndexRoute,
  AdminFaqsIndexRoute: AdminFaqsIndexRoute,
  AdminPagesIndexRoute: AdminPagesIndexRoute,
  AdminResourcesIndexRoute: AdminResourcesIndexRoute,
  AdminServicesIndexRoute: AdminServicesIndexRoute,
  AdminTestimonialsIndexRoute: AdminTestimonialsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BookConsultationRoute: BookConsultationRoute,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ResourcesRoute: ResourcesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  BlogSlugRoute: BlogSlugRoute,
  PSlugRoute: PSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ApiPublicCalendlyRoute: ApiPublicCalendlyRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
